server:
  port: ${PORT:8083}
spring:
  application:
    name: presta-products
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

prestashop:
  api_key: ${PRESTASHOP_API_KEY}
  url: ${PRESTASHOP_BASE_URL}

